import Head from 'next/head';
import Chat from '../components/Chat';
import 'react-phone-input-2/lib/style.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>ChitChat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Chat />
    </div>
  );
}
