import Head from 'next/head';
import React from 'react';
import Login from '../components/Login';

const login = () => {
  return (
    <div>
      <Head>
        <title>ChitChat-Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
};

export default login;
